#ifndef _FMOD_COMMON_H
#define _FMOD_COMMON_H

/* Macros */
#define FMOD_VERSION 0x00000000

/* FMOD_INITFLAGS */
#define FMOD_INIT_NORMAL 0x00000000
#define FMOD_INIT_3D_RIGHTHANDED 0x00000004
#define FMOD_INIT_PROFILE_ENABLE 0x00010000

/* FMOD_MODE */
#define FMOD_LOOP_OFF 0x00000001
#define FMOD_LOOP_NORMAL 0x00000002
#define FMOD_2D 0x00000008
#define FMOD_3D 0x00000010
#define FMOD_CREATESTREAM 0x00000080
#define FMOD_CREATECOMPRESSEDSAMPLE 0x00000200
#define FMOD_OPENMEMORY 0x00000800
#define FMOD_OPENMEMORY_POINT 0x10000000
#define FMOD_3D_WORLDRELATIVE 0x00080000

/* Typedefs */
typedef int FMOD_BOOL;
typedef struct FMOD_SYSTEM FMOD_SYSTEM;
typedef struct FMOD_SOUND FMOD_SOUND;
typedef struct FMOD_CHANNEL FMOD_CHANNEL;
typedef struct FMOD_CHANNELGROUP FMOD_CHANNELGROUP;
typedef unsigned int FMOD_INITFLAGS;
typedef unsigned int FMOD_MODE;

/* Enums */
typedef enum {
	FMOD_OK = 0,
	FMOD_ERR_UNSUPPORTED = 68
} FMOD_RESULT;

typedef enum {
	FMOD_SOUND_TYPE_UNKNOWN = 0,
	FMOD_SOUND_TYPE_AIFF,
        FMOD_SOUND_TYPE_FLAC = 4,
	FMOD_SOUND_TYPE_FSB,
	FMOD_SOUND_TYPE_MPEG = 9,
	FMOD_SOUND_TYPE_OGGVORBIS,
	FMOD_SOUND_TYPE_WAV = 15
} FMOD_SOUND_TYPE;

/* Struct */
typedef struct {
	float x;
	float y;
	float z;
} FMOD_VECTOR;

typedef struct {
	int cbsize;
	unsigned int length;
	const char *dlsname;
	FMOD_SOUND_TYPE suggestedsoundtype;
} FMOD_CREATESOUNDEXINFO;

#endif